version: "3.6"

volumes:
  mongo-data:

networks:
  openhim:

services:
  mediator:
    build:
      context: .
    image: openhim-mediator-passthrough
    ports:
      - "8000:8000"
    environment:
      OPENHIM_USERNAME: "{{ OPENHIM_USERNAME }}"
      OPENHIM_PASSWORD: "{{ OPENHIM_PASSWORD }}"
      OPENHIM_APIURL: "{{ OPENHIM_APIURL }}"
      OPENHIM_VERIFY_CERT: "{{ OPENHIM_VERIFY_CERT }}"
      OPENHIM_REGISTER: "{{ OPENHIM_REGISTER }}"
      OPENHIM_HEARTBEAT: "{{ OPENHIM_HEARTBEAT }}"
      MEDIATOR_URN: "{{ MEDIATOR_URN }}"
      MEDIATOR_NAME: "{{ MEDIATOR_NAME }}"
      MEDIATOR_DESCRIPTION: "{{ MEDIATOR_DESCRIPTION }}"
      MEDIATOR_URL: "{{ MEDIATOR_URL }}"
      MEDIATOR_ROUTE_0_NAME: "{{ MEDIATOR_ROUTE_0_NAME }}"
      MEDIATOR_ROUTE_0_HOST: "{{ MEDIATOR_ROUTE_0_HOST }}"
      MEDIATOR_ROUTE_0_PORT: "{{ MEDIATOR_ROUTE_0_PORT }}"
      MEDIATOR_ROUTE_0_PATH: "{{ MEDIATOR_ROUTE_0_PATH }}"
      MEDIATOR_ALLOW_ROLE: "{{ MEDIATOR_ALLOW_ROLE }}"
      MEDIATOR_UPSTREAM_URL: "{{ MEDIATOR_UPSTREAM_URL }}"
      DJANGO_SECRET_KEY: "{{ DJANGO_SECRET_KEY }}"
      DJANGO_DEBUG: "{{ DJANGO_DEBUG }}"
      DJANGO_ALLOWED_HOSTS: "{{ DJANGO_ALLOWED_HOSTS }}"

  mongo-db:
    container_name: mongo-db
    image: mongo:3.4
    networks:
      - openhim
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim-development"
      mongo_atnaUrl: "mongodb://mongo-db/openhim-development"
      NODE_ENV: "development"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
    networks:
      - openhim
    healthcheck:
     test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    networks:
      - openhim
    ports:
      - "9000:80"
    healthcheck:
     test: "curl -sS http://openhim-console || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3
